# .github/workflows/ci.yml
name: CI
on: [pull_request]

jobs:
  lint:
    name: lint            # ← 保護ルールと同じ
    runs-on: ubuntu-latest
    steps:
      - run: echo "lint ok"

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - run: echo "tests ok"

  coverage:
    name: coverage ≥85%   # ← 同じ
    runs-on: ubuntu-latest
    steps:
      - run: echo "coverage 100%"
